apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: sentinel-timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    isDefault: true
    editable: true
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
